export const relationshipQuestions = [
  "What is my biggest fear in our relationship?",
  "How do I like to be comforted when I'm upset?",
  "What's my love language?",
  "What makes me feel most appreciated?",
  "What's one thing I've always wanted to try together?",
  "What's my favorite way to spend a weekend?",
  "What do I value most in our relationship?",
  "What's something that always makes me smile?",
  "How do I prefer to handle conflicts?",
  "What's my biggest insecurity?",
  "What's my dream vacation destination?",
  "What song reminds you of me?",
  "What's my favorite memory with you?",
  "What do I need most when I'm stressed?",
  "What's one goal I've shared with you?",
  "How do I show love to you?",
  "What's my biggest pet peeve?",
  "What makes me feel secure in our relationship?",
  "What's something I'm passionate about?",
  "What's my favorite way to relax?",
  "What do I appreciate most about you?",
  "What's one thing I struggle with?",
  "What's my favorite quality in a partner?",
  "How do I like to celebrate special occasions?",
  "What's something I've always been proud of?",
  "What makes me feel loved?",
  "What's my biggest dream for our future?",
  "What's one thing I can't live without?",
  "What's my favorite thing about our relationship?",
  "How do I express when I'm hurt?",
  "What's something I wish we did more often?",
  "What's my favorite type of date?",
  "What's one thing I've learned from you?",
  "What do I find most attractive about you?",
  "What's my favorite season and why?",
  "What's one thing I want to improve about myself?",
  "What makes me feel understood?",
  "What's my biggest turn-on?",
  "What's something I'm grateful for every day?",
  "What's my idea of a perfect day together?",
  "How do I like to receive apologies?",
  "What's something I admire about you?",
  "What's my favorite childhood memory?",
  "What do I need to feel emotionally safe?",
  "What's one habit of mine you've noticed?",
  "What's my favorite meal or food?",
  "How do I show I'm angry or frustrated?",
  "What's something I've always wanted to learn?",
  "What's my biggest relationship goal?",
  "What's one thing that always cheers me up?",
  "What do I value most in communication?",
  "What's my favorite way to show affection?",
  "What's something I've shared about my family?",
  "What makes me feel respected?",
  "What's my favorite thing to do with you?",
  "What's one thing I'm working on emotionally?",
  "What's my favorite type of music or artist?",
  "How do I react to surprises?",
  "What's something I've told you I'm afraid of?",
  "What's my favorite way to spend quality time?",
  "What do I need most from our relationship?",
  "What's one thing I've always been curious about?",
  "What's my biggest dealbreaker in relationships?",
  "What makes me feel prioritized?",
  "What's my favorite movie or TV show?",
  "How do I like to be supported?",
  "What's something I've mentioned wanting to change?",
  "What's my favorite hobby or interest?",
  "What makes me feel heard?",
  "What's one thing I've shared about my past?",
  "What's my favorite way to be surprised?",
  "What do I find most challenging in relationships?",
  "What's something I value about our connection?",
  "What's my favorite color and why?",
  "How do I express gratitude?",
  "What's one thing I've told you I'm proud of?",
  "What makes me feel valued?",
  "What's my favorite physical touch?",
  "What's something I've mentioned bothers me?",
  "What's my ideal way to resolve an argument?",
  "What do I appreciate about your personality?",
  "What's my favorite book or author?",
  "How do I show I care about you?",
  "What's something I've said I want to achieve?",
  "What makes me feel comfortable opening up?",
  "What's my favorite season of our relationship?",
  "What's one thing I've mentioned I miss?",
  "What's my favorite type of gift?",
  "How do I react when I'm jealous?",
  "What's something I've shared about my beliefs?",
  "What makes me feel connected to you?",
  "What's my favorite place we've been together?",
  "What's one thing I've said I need more of?",
  "What's my favorite quality about myself?",
  "How do I show vulnerability?",
  "What's something I've told you excites me?",
  "What makes me feel safe with you?",
  "What's my favorite way to laugh together?",
  "What's one thing I've mentioned I regret?",
  "What's my biggest strength in relationships?",
  "What do I find most romantic?",
  "What's my favorite way you show love?",
  "What's something I've shared about my future?",
  "What makes me feel beautiful or handsome?",
  "What's my favorite inside joke we have?",
  "How do I express disappointment?",
  "What's one thing I've said I'm insecure about?",
  "What's my favorite thing about your body?",
  "What makes me feel important to you?",
  "What's my favorite memory of us laughing?",
  "What's something I've mentioned I'm scared of losing?",
  "What's my favorite way to be intimate?",
  "How do I show I'm happy?",
  "What's one thing I've told you I admire about us?",
  "What makes me feel truly known by you?",
  "What's my favorite promise we've made?",
  "What's something I've shared about my dreams?",
  "What's my biggest hope for our love?"
];

export function getRandomQuestions(count: number): string[] {
  const shuffled = [...relationshipQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}